name: Parse playerInfo.dat

on:
  push:
    paths:
      - 'tools/**'
      - '.github/workflows/**'
  workflow_dispatch: {}

jobs:
  parse:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true

      - name: Run parser
        run: |
          mkdir -p out
          python tools/parse_playerinfo.py tools/sample_data/playerInfo.dat --out out/ || echo "parser not ready yet"

      - name: Create GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          installation-id: ${{ secrets.INSTALLATION_ID }}

      # Choose ONE option:

      # Option A: commit results directly to current branch
      - name: Commit outputs
        env:
          APP_TOKEN: ${{ steps.app-token.outputs.token }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          git config user.name "the-tower-agent[bot]"
          git config user.email "the-tower-agent[bot]@users.noreply.github.com"
          git add out/ || true
          git commit -m "ci: update parsed outputs" || exit 0
          git push https://${APP_TOKEN}@github.com/${REPO}.git HEAD:${BRANCH}

      # Option B (recommended if branch protection on main): open a PR
      # - uses: peter-evans/create-pull-request@v6
      #   with:
      #     token: ${{ steps.app-token.outputs.token }}
      #     branch: bot/update-parsed-output
      #     commit-message: "ci: update parsed outputs"
      #     title: "CI: Update parsed outputs"
      #     body: "Automated update created by the GitHub App."
